/** Action catalog กลางของ Audit Log — ห้ามพิมพ์ string สดใน service */
export const AUDIT_ACTIONS = {
  // Auth / Account
  AUTH_LOGIN_SUCCESS: "AUTH.LOGIN_SUCCESS",
  AUTH_LOGIN_FAILURE: "AUTH.LOGIN_FAILURE",
  AUTH_REGISTER: "AUTH.REGISTER",
  USER_PASSWORD_CHANGE: "USER.PASSWORD_CHANGE",
  USER_PASSWORD_SET: "USER.PASSWORD_SET",
  USER_PROFILE_UPDATE: "USER.PROFILE_UPDATE",
  USER_SECURITY_PIN_SET: "USER.SECURITY_PIN_SET",
  USER_SECURITY_PIN_CHANGE: "USER.SECURITY_PIN_CHANGE",
  USER_SECURITY_PIN_LOCKOUT: "USER.SECURITY_PIN_LOCKOUT",
  ADMIN_STEP_UP_SUCCESS: "ADMIN.STEP_UP_SUCCESS",
  ADMIN_STEP_UP_FAILURE: "ADMIN.STEP_UP_FAILURE",
  ADMIN_PASSWORD_RESET: "ADMIN.PASSWORD_RESET",
  ADMIN_SECURITY_PIN_RESET: "ADMIN.SECURITY_PIN_RESET",
  ADMIN_USER_ROLE_CHANGE: "ADMIN.USER_ROLE_CHANGE",
  ADMIN_USER_STATUS_CHANGE: "ADMIN.USER_STATUS_CHANGE",

  // Support / Chat
  SUPPORT_CASE_CREATE: "SUPPORT.CASE_CREATE",
  SUPPORT_CASE_CLAIM: "SUPPORT.CASE_CLAIM",
  SUPPORT_CASE_ASSIGN: "SUPPORT.CASE_ASSIGN",
  SUPPORT_CASE_STATUS_CHANGE: "SUPPORT.CASE_STATUS_CHANGE",
  SUPPORT_CASE_CLOSE: "SUPPORT.CASE_CLOSE",
  SUPPORT_CASE_REPLY_PUBLIC: "SUPPORT.CASE_REPLY_PUBLIC",
  SUPPORT_CASE_NOTE_INTERNAL: "SUPPORT.CASE_NOTE_INTERNAL",
  CHAT_CONVERSATION_CREATE: "CHAT.CONVERSATION_CREATE",
  CHAT_MESSAGE_SEND: "CHAT.MESSAGE_SEND",

  // Template / Events (sensitive)
  TEMPLATE_PUBLISH: "TEMPLATE.PUBLISH",
  TEMPLATE_ROLLBACK: "TEMPLATE.ROLLBACK",
  EVENT_DELETE: "EVENT.DELETE",

  // Logs
  ADMIN_LOG_EXPORT: "ADMIN.LOG_EXPORT",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_RESOURCE_TYPES = [
  "user",
  "event",
  "template",
  "support_case",
  "conversation",
  "log",
] as const;

export type AuditResourceType = (typeof AUDIT_RESOURCE_TYPES)[number];
